"""PM agent: picks next feature from state.yaml backlog, opens a labelled GH issue."""

import argparse
import asyncio
import re
import subprocess
import sys
from datetime import UTC, datetime
from pathlib import Path

from agents.lib import gh, kill_switch, labels, product_state, prompts
from agents.lib.anthropic import run_agent

_DEFAULT_STATE = Path("docs/product/state.yaml")
_DEFAULT_VISION = Path("docs/product/vision.md")


def _vision_text(path: Path) -> str:
    text = path.read_text() if path.exists() else ""
    body = re.sub(r"^# .+$", "", text, flags=re.MULTILINE).strip()
    return body


async def run(state_path: Path, vision_path: Path, *, dry_run: bool) -> str:
    """Returns 'skipped' | 'picked' | 'generated'."""
    state = product_state.load(state_path)
    vision = _vision_text(vision_path)
    repo = gh.repo()
    open_issues = list(repo.get_issues(state="open", labels=[labels.AGENT_BUILD]))

    if not vision:
        return "skipped"
    if len(open_issues) >= state.max_open_agent_issues:
        return "skipped"

    user_prompt = (
        f"VISION:\n{vision}\n\n"
        f"OPEN_ISSUES ({len(open_issues)}):\n"
        + "\n".join(f"- #{i.number} {i.title}" for i in open_issues)
        + "\n\nSTATE:\n"
        + f"backlog: {[{'id': b.id, 'title': b.title} for b in state.backlog]}\n"
        + f"in_progress: {[{'id': b.id, 'title': b.title} for b in state.in_progress]}\n"
        + f"shipped: {[b.title for b in state.shipped]}\n"
    )
    system = prompts.load("product_manager")
    result = await run_agent(prompt=user_prompt, system=system, max_turns=3, allowed_tools=[])
    text = _extract_text(result.messages)
    decision = _parse_decision(text)

    if decision["kind"] == "SKIP":
        return "skipped"

    if decision["kind"] == "PICK" and not any(b.id == decision["id"] for b in state.backlog):
        raise ValueError(
            f"PM picked ID {decision['id']!r} not in backlog. "
            f"Available: {[b.id for b in state.backlog]}"
        )

    if not dry_run:
        body = decision["body"] + f"\n\n_Opened autonomously by Product Manager agent at {datetime.now(UTC).isoformat()}._"
        issue = repo.create_issue(
            title=decision["title"],
            body=body,
            labels=[labels.AGENT_BUILD],
        )
        if decision["kind"] == "PICK":
            state.start(decision["id"], issue_number=issue.number)
        elif decision["kind"] == "GENERATE":
            new_id = f"B{1 + len(state.backlog) + len(state.shipped) + len(state.in_progress):03d}"
            state.backlog.append(product_state.Item(
                id=new_id, title=decision["title"],
                priority="normal", rationale="generated by PM",
                added_by="pm-agent", issue_number=issue.number,
            ))
            state.start(new_id, issue_number=issue.number)
        state.last_pm_run = datetime.now(UTC).isoformat()
        product_state.save(state_path, state)

        subprocess.run(
            ["gh", "workflow", "run", "planner.yml", "-f", f"issue_number={issue.number}"],
            check=False,
        )

    return "picked" if decision["kind"] == "PICK" else "generated"


def _extract_text(messages: list[object]) -> str:
    parts: list[str] = []
    for m in messages:
        if isinstance(m, dict) and m.get("type") == "text" and "text" in m:
            parts.append(str(m["text"]))
        elif hasattr(m, "text"):
            parts.append(str(m.text))
    return "\n".join(parts).strip()


def _parse_decision(text: str) -> dict[str, str]:
    """Parse structured LLM response. Returns dict with 'kind', 'id', 'title', 'body'."""
    first = text.splitlines()[0] if text else ""
    if first.startswith("DECISION: SKIP"):
        return {"kind": "SKIP", "id": "", "title": "", "body": ""}

    if "DECISION: PICK" in first:
        kind = "PICK"
    elif "DECISION: GENERATE" in first:
        kind = "GENERATE"
    else:
        raise ValueError(f"Unrecognised PM decision line: {first!r}")
    id_match = re.search(r"^ID:\s*(\S+)", text, flags=re.MULTILINE)
    title_match = re.search(r"^TITLE:\s*(.+)$", text, flags=re.MULTILINE)
    body_match = re.search(r"^BODY:\s*\n(.+)", text, flags=re.DOTALL | re.MULTILINE)
    return {
        "kind": kind,
        "id": id_match.group(1) if id_match else "",
        "title": title_match.group(1).strip() if title_match else "",
        "body": body_match.group(1).strip() if body_match else "",
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="agents.product_manager")
    parser.add_argument("--state", type=Path, default=_DEFAULT_STATE)
    parser.add_argument("--vision", type=Path, default=_DEFAULT_VISION)
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args(argv)
    kill_switch.exit_if_paused()
    result = asyncio.run(run(args.state, args.vision, dry_run=args.dry_run))
    print(f"pm: {result}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
